// AgentOs.Tests/Llm/RemoteAgentTests.cs
// Unit tests for the "remote dev-IDE agent" runtime: the dispatch broker + the RemoteAgentLlmClient
// that wraps a remote reply as a zero-cost LlmResponse.

using System;
using System.Threading.Tasks;
using AgentOs.Domain.Llm;
using AgentOs.Modules.Llm;
using AgentOs.Modules.RemoteAgent;
using Microsoft.Extensions.Logging.Abstractions;
using Shouldly;
using Xunit;

namespace AgentOs.Tests.Llm;

public class RemoteAgentTests
{
    [Fact]
    public async Task Broker_DispatchThenComplete_ReturnsAgentResult()
    {
        var broker = new InProcessRemoteAgentBroker();
        using var reg = broker.RegisterAgent("agent-1");
        RemoteExecRequest? dispatched = null;
        broker.RequestDispatched += r => dispatched = r;

        var task = broker.DispatchAsync(new RemoteExecRequest("id1", "sys", "user", "model"), TimeSpan.FromSeconds(5));
        dispatched.ShouldNotBeNull();
        dispatched!.Id.ShouldBe("id1");

        broker.Complete(new RemoteExecResult("id1", true, "result text", null));

        var result = await task;
        result.Ok.ShouldBeTrue();
        result.Content.ShouldBe("result text");
    }

    [Fact]
    public async Task Broker_NoAgent_DispatchThrows()
    {
        var broker = new InProcessRemoteAgentBroker();
        broker.HasAgent.ShouldBeFalse();

        await Should.ThrowAsync<InvalidOperationException>(
            () => broker.DispatchAsync(new RemoteExecRequest("x", "s", "u", "m"), TimeSpan.FromSeconds(1)));
    }

    [Fact]
    public async Task Broker_NoResponse_TimesOut()
    {
        var broker = new InProcessRemoteAgentBroker();
        using var reg = broker.RegisterAgent("agent-1");

        await Should.ThrowAsync<TimeoutException>(
            () => broker.DispatchAsync(new RemoteExecRequest("id", "s", "u", "m"), TimeSpan.FromMilliseconds(50)));
    }

    [Fact]
    public void Broker_AgentDisposed_NoLongerConnected()
    {
        var broker = new InProcessRemoteAgentBroker();
        var reg = broker.RegisterAgent("agent-1");
        broker.HasAgent.ShouldBeTrue();
        reg.Dispose();
        broker.HasAgent.ShouldBeFalse();
    }

    [Fact]
    public async Task Client_WithAgent_ReturnsContent_AtZeroCost()
    {
        var broker = new InProcessRemoteAgentBroker();
        using var reg = broker.RegisterAgent("agent-1");
        // Auto-answer every dispatched request as the remote agent would.
        broker.RequestDispatched += r => broker.Complete(new RemoteExecResult(r.Id, true, "// generated by dev IDE", null));

        var client = new RemoteAgentLlmClient(broker, NullLogger<RemoteAgentLlmClient>.Instance);
        var response = await client.SendAsync(new LlmRequest("sys", "build X", "claude-sonnet-4"));

        response.Content.ShouldBe("// generated by dev IDE");
        response.CostUsd.ShouldBe(0m);
        response.InputTokens.ShouldBe(0);
        response.OutputTokens.ShouldBe(0);
        response.Provider.ShouldBe("RemoteAgent");
    }

    [Fact]
    public async Task Client_NoAgent_ThrowsLlmException()
    {
        var broker = new InProcessRemoteAgentBroker();
        var client = new RemoteAgentLlmClient(broker, NullLogger<RemoteAgentLlmClient>.Instance);

        await Should.ThrowAsync<LlmException>(
            () => client.SendAsync(new LlmRequest("sys", "build X", "model")));
    }

    [Fact]
    public async Task Client_AgentReportsFailure_ThrowsLlmException()
    {
        var broker = new InProcessRemoteAgentBroker();
        using var reg = broker.RegisterAgent("agent-1");
        broker.RequestDispatched += r => broker.Complete(new RemoteExecResult(r.Id, false, "", "compile failed"));

        var client = new RemoteAgentLlmClient(broker, NullLogger<RemoteAgentLlmClient>.Instance);

        var ex = await Should.ThrowAsync<LlmException>(
            () => client.SendAsync(new LlmRequest("sys", "build X", "model")));
        ex.Message.ShouldContain("compile failed");
    }
}
