// AgenticSdlc.Domain/Testing/TestArtifact.cs
// Phase 3 — Output of TestingAgent — the xUnit test case set.

using System.Collections.Generic;
using AgenticSdlc.Domain.Code;

namespace AgenticSdlc.Domain.Testing;

/// <summary>
/// The test case set generated by <c>ITestingAgent</c>.
/// </summary>
/// <param name="Framework">Test framework (<c>xUnit</c>, <c>NUnit</c>, ...). Default <c>xUnit</c>.</param>
/// <param name="Files">List of test files (path + content).</param>
/// <param name="HappyPathCount">Number of happy-path tests.</param>
/// <param name="EdgeCaseCount">Number of edge-case tests.</param>
/// <param name="ErrorCaseCount">Number of error-case tests.</param>
/// <param name="EstimatedCoveragePercent">Estimated coverage (%) — agent self-reported, NOT actually measured.</param>
/// <param name="Metrics">Agent metric.</param>
public sealed record TestArtifact(
    string Framework,
    IReadOnlyList<CodeFile> Files,
    int HappyPathCount,
    int EdgeCaseCount,
    int ErrorCaseCount,
    int EstimatedCoveragePercent,
    AgentMetrics Metrics)
{
    /// <summary>Total number of test cases (happy + edge + error).</summary>
    public int TotalCount => HappyPathCount + EdgeCaseCount + ErrorCaseCount;
}
