// AgenticSdlc.Domain/Code/CodeArtifact.cs
// Phase 3 — Output of CodingAgent — source code as a file collection.

using System.Collections.Generic;

namespace AgenticSdlc.Domain.Code;

/// <summary>
/// The source code set generated by <c>ICodingAgent</c>.
/// </summary>
/// <param name="ProjectName">Name of the generated project (e.g. <c>ProductCatalog</c>).</param>
/// <param name="Architecture">Architecture applied (default <c>"Clean Architecture"</c>).</param>
/// <param name="Files">List of files (path + content + language).</param>
/// <param name="Notes">Additional notes from the agent (e.g. assumptions, TODO).</param>
/// <param name="Metrics">Agent metric.</param>
public sealed record CodeArtifact(
    string ProjectName,
    string Architecture,
    IReadOnlyList<CodeFile> Files,
    string? Notes,
    AgentMetrics Metrics);

/// <summary>A single source code file.</summary>
/// <param name="Path">Relative path (e.g. <c>src/Domain/Product.cs</c>).</param>
/// <param name="Content">File content.</param>
/// <param name="Language">Language (<c>csharp</c>, <c>json</c>, <c>sql</c>, ...).</param>
public sealed record CodeFile(string Path, string Content, string Language = "csharp");
